version: '3.8'

services:
  mongodb:
    image: mongo:7
    container_name: aibuytech-mongodb
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpassword
      MONGO_INITDB_DATABASE: aibuytech
    ports:
      - '27017:27017'
    volumes:
      - mongodb_data:/data/db
    networks:
      - aibuytech-network

  mongo-express:
    image: mongo-express:latest
    container_name: aibuytech-mongo-express
    restart: always
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: rootpassword
      ME_CONFIG_MONGODB_URL: mongodb://root:rootpassword@mongodb:27017/
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: admin123
    ports:
      - '8081:8081'
    depends_on:
      - mongodb
    networks:
      - aibuytech-network

volumes:
  mongodb_data:
    driver: local

networks:
  aibuytech-network:
    driver: bridge
