version: '3.8'

services:
  mongodb:
    image: mongo:7
    container_name: aibuytech-mongodb
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpassword
      MONGO_INITDB_DATABASE: aibuytech
    ports:
      - '27017:27017'
    volumes:
      - mongodb_data:/data/db
    networks:
      - aibuytech-network

  mongo-express:
    image: mongo-express:latest
    container_name: aibuytech-mongo-express
    restart: always
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: rootpassword
      ME_CONFIG_MONGODB_URL: mongodb://root:rootpassword@mongodb:27017/
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: admin123
    ports:
      - '8081:8081'
    depends_on:
      - mongodb
    networks:
      - aibuytech-network

  # VectorDB(milvus)
  etcd:
    container_name: aibuytech-milvus-etcd
    image: quay.io/coreos/etcd:v3.5.5
    environment:
      ETCD_AUTO_COMPACTION_MODE: revision
      ETCD_AUTO_COMPACTION_RETENTION: "1000"
      ETCD_QUOTA_BACKEND_BYTES: "4294967296"
      ETCD_SNAPSHOT_COUNT: "50000"
    command: >
      etcd -advertise-client-urls http://etcd:2379
           -listen-client-urls http://0.0.0.0:2379
           -listen-peer-urls http://0.0.0.0:2380
           -initial-advertise-peer-urls http://etcd:2380
           -initial-cluster etcd=http://etcd:2380
           -initial-cluster-state new
           -name etcd
    volumes:
      - ./volumes/etcd:/etcd-data
    networks:
      - aibuytech-network

  minio:
    container_name: aibuytech-milvus-minio
    image: minio/minio:RELEASE.2023-09-30T07-02-29Z
    environment:
      MINIO_ACCESS_KEY: minioadmin
      MINIO_SECRET_KEY: minioadmin
    command: server /minio_data --console-address ":9001"
    volumes:
      - ./volumes/minio:/minio_data
    ports:
      - "9001:9001"
    networks:
      - aibuytech-network

  milvus:
    container_name: aibuytech-milvus-standalone
    image: milvusdb/milvus:v2.4.7
    command: ["milvus", "run", "standalone"]
    environment:
      ETCD_ENDPOINTS: etcd:2379
      MINIO_ADDRESS: minio:9000
      MINIO_ACCESS_KEY: minioadmin
      MINIO_SECRET_KEY: minioadmin
      MINIO_USE_SSL: "false"
      DATA_NODE_DATA_PATH: /var/lib/milvus
      MILVUS_LOG_LEVEL: info
    volumes:
      - ./volumes/milvus:/var/lib/milvus
    ports:
      - "19530:19530"  # gRPC
      - "9091:9091"    # REST
    depends_on:
      - etcd
      - minio
    networks:
      - aibuytech-network

  # Milvus UI (Attu)
  attu:
    container_name: aibuytech-milvus-attu
    image: zilliz/attu:v2.4.7
    environment:
      MILVUS_URL: milvus:19530
    ports:
      - "8000:3000"
    depends_on:
      - milvus
    networks:
      - aibuytech-network

volumes:
  mongodb_data:
    driver: local  
  volumes_etcd:
    driver: local
  volumes_minio:
    driver: local
  volumes_milvus:
    driver: local

networks:
  aibuytech-network:
    driver: bridge
